name: lhmp-thor-magni-challenge-extra
channels:
  - anaconda
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - absl-py=2.1.0
  - asttokens=2.4.1
  - blas=1.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - bzip2=1.0.8
  - c-ares=1.26.0
  - ca-certificates=2024.2.2
  - certifi=2024.2.2
  - colorama=0.4.6
  - comm=0.2.1
  - contourpy=1.2.0
  - cycler=0.12.1
  - dbus=1.13.18
  - debugpy=1.8.1
  - decorator=5.1.1
  - exceptiongroup=1.2.0
  - executing=2.0.1
  - expat=2.5.0
  - filelock=3.13.1
  - fontconfig=2.14.2
  - fonttools=4.48.1
  - freetype=2.12.1
  - gettext=0.21.1
  - glib=2.78.3
  - glib-tools=2.78.3
  - gmp=6.3.0
  - gmpy2=2.1.2
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - icu=58.2
  - importlib-metadata=7.0.1
  - importlib_metadata=7.0.1
  - intel-openmp=2021.4.0
  - ipykernel=6.29.2
  - ipython=8.21.0
  - jedi=0.19.1
  - jinja2=3.1.3
  - joblib=1.3.2
  - jpeg=9e
  - jupyter_client=8.6.0
  - jupyter_core=5.7.1
  - keyutils=1.6.1
  - kiwisolver=1.4.5
  - krb5=1.20.1
  - lcms2=2.12
  - ld_impl_linux-64=2.40
  - lerc=3.0
  - libabseil=20240116.1
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libclang=10.0.1
  - libdeflate=1.17
  - libedit=3.1.20191231
  - libevent=2.1.12
  - libexpat=2.5.0
  - libffi=3.4.2
  - libgcc-ng=13.2.0
  - libgfortran-ng=13.2.0
  - libgfortran5=13.2.0
  - libglib=2.78.3
  - libgomp=13.2.0
  - libgrpc=1.61.1
  - libiconv=1.17
  - liblapack=3.9.0
  - libllvm10=10.0.1
  - libnsl=2.0.1
  - libopenblas=0.3.26
  - libpng=1.6.42
  - libpq=12.17
  - libprotobuf=4.25.2
  - libre2-11=2023.09.01
  - libsodium=1.0.18
  - libsqlite=3.45.1
  - libstdcxx-ng=13.2.0
  - libtiff=4.5.1
  - libuuid=2.38.1
  - libwebp-base=1.3.2
  - libxcb=1.16
  - libxkbcommon=1.0.1
  - libxml2=2.9.14
  - libzlib=1.2.13
  - lightning-utilities=0.10.1
  - llvm-openmp=8.0.1
  - markdown=3.5.2
  - markupsafe=2.1.5
  - matplotlib=3.8.2
  - matplotlib-base=3.8.2
  - matplotlib-inline=0.1.6
  - mkl=2021.4.0
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - munkres=1.1.4
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - networkx=3.2.1
  - nspr=4.35
  - nss=3.97
  - openjpeg=2.5.0
  - openssl=3.2.1
  - packaging=23.2
  - parso=0.8.3
  - pcre2=10.42
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=10.2.0
  - pip=22.3.1
  - platformdirs=4.2.0
  - ply=3.11
  - prompt-toolkit=3.0.42
  - psutil=5.9.8
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pygments=2.17.2
  - pyparsing=3.1.1
  - pyqt=5.15.10
  - pyqt5-sip=12.13.0
  - python=3.10.8
  - python-dateutil=2.8.2
  - python_abi=3.10
  - pytorch=2.2.0
  - pytorch-mutex=1.0
  - pyyaml=6.0.1
  - pyzmq=25.1.2
  - qt-main=5.15.2
  - re2=2023.09.01
  - readline=8.2
  - scikit-learn=1.3.0
  - scipy=1.12.0
  - setuptools=69.0.3
  - sip=6.7.12
  - six=1.16.0
  - sqlite=3.45.1
  - stack_data=0.6.2
  - sympy=1.12
  - tensorboard=2.16.2
  - threadpoolctl=3.3.0
  - tk=8.6.13
  - tomli=2.0.1
  - torchmetrics=1.2.1
  - tqdm=4.66.2
  - traitlets=5.14.1
  - typing_extensions=4.9.0
  - tzdata=2024a
  - unicodedata2=15.1.0
  - wcwidth=0.2.13
  - werkzeug=3.0.1
  - wheel=0.42.0
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xz=5.4.5
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.17.0
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
    - aiohttp==3.9.3
    - aiosignal==1.3.1
    - altair==4.2.0
    - async-timeout==4.0.3
    - attrs==23.2.0
    - blinker==1.7.0
    - cachetools==5.3.2
    - charset-normalizer==3.3.2
    - click==8.1.7
    - entrypoints==0.4
    - frozenlist==1.4.1
    - fsspec==2024.2.0
    - gitdb==4.0.11
    - gitpython==3.1.41
    - grpcio==1.51.3
    - idna==3.6
    - jsonschema==4.21.1
    - jsonschema-specifications==2023.12.1
    - lightning==2.2.0.post0
    - markdown-it-py==3.0.0
    - mdurl==0.1.2
    - msgpack==1.0.7
    - multidict==6.0.5
    - numpy==1.24.1
    - pandas==1.5.3
    - plotly==5.12.0
    - protobuf==3.20.3
    - pyarrow==15.0.0
    - pydeck==0.8.1b0
    - pympler==1.0.1
    - pytorch-lightning==2.2.0.post0
    - pytz==2024.1
    - ray==2.5.1
    - referencing==0.33.0
    - requests==2.31.0
    - rich==13.7.0
    - rpds-py==0.17.1
    - semver==3.0.2
    - smmap==5.0.1
    - streamlit==1.18.1
    - tenacity==8.2.3
    - tensorboard-data-server==0.7.2
    - tensorboardx==2.6.2.2
    - toml==0.10.2
    - toolz==0.12.1
    - tornado==6.4
    - tzlocal==5.2
    - urllib3==2.2.0
    - validators==0.22.0
    - watchdog==4.0.0
    - yarl==1.9.4
